name: <+service.variables.name>
image: <+artifact.image>
canaryName: <+service.variables.canaryName>
stableName: <+service.variables.stableName>
endpoint: color
canaryEndpoint: color-canary
stableEndpoint: color-stable
splitTraffic: false

replicas: 2
namespace: <+infra.namespace>

frontend:
  title: Istio - Canary
  loadBalancer: <+serviceVariables.loadBalancer>
  uiPath: <+service.variables.uiPath>
  image: us.gcr.io/sales-209522/continuous-requests:110
